name: checkov
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  checkov:
    name: checkov
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Run Checkov action
        id: checkov
        uses: bridgecrewio/checkov-action@2.2.281
        with:
          directory: /
